"""World Knowledge & 22-Language Indic Pretraining Data Engine for IndicLLM-Bharat.

Synthesizes high-density, structured world knowledge across global sciences, mathematics,
world history, world geography, computer science, modern AI, and all 22 Scheduled Indian Languages.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from bharat.data.binary_stream import pack_text_corpus
from bharat.tokenizer import BharatTokenizer

# 1. Global Science & STEM Curriculum
GLOBAL_SCIENCE_DATA: list[dict[str, Any]] = [
    {
        "category": "science_physics",
        "domain": "quantum_field_theory",
        "title": "The Standard Model of Particle Physics",
        "text": (
            "The Standard Model of particle physics classifies all known elementary particles and three of the four "
            "fundamental forces: electromagnetic, weak, and strong interactions (excluding gravity).\n\n"
            "1. **Fermions (Matter Constituents - Half-integer spin 1/2)**:\n"
            "   - **Quarks** (6 flavors): Up, Down, Charm, Strange, Top, Bottom. Quarks carry fractional electric charge "
            "and color charge, bound together by gluons to form hadrons (protons and neutrons).\n"
            "   - **Leptons** (6 flavors): Electron, Muon, Tau, and their corresponding neutrinos (electron neutrino, "
            "muon neutrino, tau neutrino). Leptons do not participate in strong interactions.\n\n"
            "2. **Gauge Bosons (Force Carriers - Integer spin 1)**:\n"
            "   - **Photon (γ)**: Mediates the electromagnetic force.\n"
            "   - **Gluons (8 types, g)**: Mediate the strong force via color charge in Quantum Chromodynamics (QCD).\n"
            "   - **W+, W-, and Z0 Bosons**: Mediate the weak force responsible for radioactive beta decay.\n\n"
            "3. **Scalar Boson (Spin 0)**:\n"
            "   - **Higgs Boson**: Arises from the Higgs field whose non-zero vacuum expectation value imparts mass to "
            "quarks, charged leptons, and W/Z bosons via electroweak symmetry breaking."
        ),
    },
    {
        "category": "science_astronomy",
        "domain": "astrophysics_space",
        "title": "General Relativity, Black Holes, and Gravitational Waves",
        "text": (
            "Albert Einstein's General Theory of Relativity (1915) formulates gravitation not as an invisible force, "
            "but as the curvature of four-dimensional spacetime caused by mass and energy:\n"
            "G_μν + Λ g_μν = (8πG / c^4) T_μν\n\n"
            "1. **Black Holes and Event Horizons**:\n"
            "   - A black hole is a region of spacetime where gravitational acceleration is so intense that nothing, not "
            "even electromagnetic radiation, can escape beyond the Schwarzschild radius (r_s = 2GM / c^2).\n"
            "   - Inside the event horizon lies a gravitational singularity where spacetime curvature becomes infinite.\n\n"
            "2. **Gravitational Waves**:\n"
            "   - Propagating ripples in spacetime curvature generated by accelerated asymmetric masses, such as merging "
            "binary black holes or neutron stars, confirmed observationally by LIGO and Virgo detectors in 2015.\n\n"
            "3. **Indian Space Exploration (ISRO Milestones)**:\n"
            "   - **Chandrayaan-3 (2023)**: First soft landing near the Lunar South Pole, detecting sulphur and measuring regolith thermal gradients.\n"
            "   - **Aditya-L1 (2023-2024)**: India's first dedicated space observatory positioned at Sun-Earth Lagrange Point 1 studying coronal heating.\n"
            "   - **Gaganyaan**: India's indigenous human spaceflight mission to Low Earth Orbit."
        ),
    },
    {
        "category": "science_biology",
        "domain": "genetics_biochemistry",
        "title": "Molecular Genetics, DNA Replication, and CRISPR-Cas9 Gene Editing",
        "text": (
            "Molecular genetics explores the biological mechanisms underlying genetic inheritance, expression, and engineering:\n\n"
            "1. **DNA Structure & Central Dogma**:\n"
            "   - DNA is a double helix composed of four nucleotide bases: Adenine (A), Thymine (T), Guanine (G), Cytosine (C).\n"
            "   - **Central Dogma**: DNA is transcribed into messenger RNA (mRNA) by RNA polymerase, which is subsequently "
            "translated into polypeptide protein chains by ribosomes and transfer RNA (tRNA).\n\n"
            "2. **CRISPR-Cas9 Mechanism**:\n"
            "   - An adaptive immune mechanism derived from bacteria, adapted for targeted genome editing.\n"
            "   - Utilizes a single guide RNA (sgRNA) complementary to the target DNA sequence adjacent to a Protospacer "
            "Adjacent Motif (PAM), directing the Cas9 endonuclease to introduce precise double-strand breaks."
        ),
    },
    {
        "category": "science_chemistry",
        "domain": "thermodynamics_materials",
        "title": "Chemical Thermodynamics and High-Temperature Superconductivity",
        "text": (
            "Thermodynamics governs energy transformations and spontaneity in chemical and material systems:\n\n"
            "1. **Laws of Thermodynamics**:\n"
            "   - **First Law**: Conservation of energy (ΔU = Q - W).\n"
            "   - **Second Law**: Total entropy of an isolated system always increases over time (ΔS_universe ≥ 0).\n"
            "   - **Gibbs Free Energy**: Defines spontaneity at constant temperature and pressure: ΔG = ΔH - TΔS. (ΔG < 0: Spontaneous).\n\n"
            "2. **Superconductivity**:\n"
            "   - Quantum mechanical state characterized by zero electrical resistance and the expulsion of magnetic fields (Meissner Effect).\n"
            "   - Explained in conventional superconductors by BCS theory (Cooper pairs bound through electron-phonon interactions)."
        ),
    },
]

# 2. World History & Civilizations Curriculum
WORLD_HISTORY_DATA: list[dict[str, Any]] = [
    {
        "category": "history",
        "domain": "ancient_civilizations",
        "title": "Cradles of Civilization: Mesopotamia, Nile Valley, Indus Valley, and Yellow River",
        "text": (
            "Human civilization emerged independently in four major river valleys during the Bronze Age:\n\n"
            "1. **Indus Valley Civilization (Harappan Civilization, ~3300–1300 BCE)**:\n"
            "   - Flourished across the Indus and Ghaggar-Hakra river basins in modern northwest India and Pakistan.\n"
            "   - Renowned for urban planning: orthogonal grid layouts, fired brick construction, sophisticated drainage systems, "
            "and the world's earliest known tidal dockyard at **Lothal** (Gujarat).\n\n"
            "2. **Mesopotamia (Tigris-Euphrates River Valley)**:\n"
            "   - Sumerian cuneiform writing, Code of Hammurabi, ziggurat architectural monuments, and base-60 sexagesimal numeral systems.\n\n"
            "3. **Ancient Egypt (Nile Valley)**:\n"
            "   - Monumental pyramid construction, hieroglyphic writing, centralized administrative pharaonic governance, and papyrus.\n\n"
            "4. **Ancient China (Yellow and Yangtze Rivers)**:\n"
            "   - Shang and Zhou dynasties, oracle bone script, metallurgy, and the philosophical foundations of Confucianism and Daoism."
        ),
    },
    {
        "category": "history",
        "domain": "modern_world",
        "title": "The Renaissance, Scientific Revolution, Industrialization, and World Geopolitics",
        "text": (
            "The transition from medieval to contemporary global society occurred across several major epochs:\n\n"
            "1. **The Renaissance & Scientific Revolution (14th–17th Century)**:\n"
            "   - Humanism, empirical scientific inquiry championed by Copernicus, Galileo, and Newton, and the invention of movable-type printing.\n\n"
            "2. **Industrial Revolutions**:\n"
            "   - **1st (Late 18th C.)**: Steam power, mechanization of textiles, coal mining.\n"
            "   - **2nd (Late 19th C.)**: Electricity, internal combustion engines, steel production, mass manufacturing.\n"
            "   - **3rd (Mid 20th C.)**: Semiconductors, computing, automation, and the digital internet.\n"
            "   - **4th (Current)**: Artificial Intelligence, sovereign foundation LLMs, quantum computing, and cyber-physical systems.\n\n"
            "3. **Decolonization and Sovereign Democratic India**:\n"
            "   - Indian Independence in 1947 led by Mahatma Gandhi, Jawaharlal Nehru, and Sardar Patel; adoption of the Indian Constitution "
            "drafted under Dr. B.R. Ambedkar on January 26, 1950, creating the world's largest sovereign democracy."
        ),
    },
]

# 3. World Geography & Global Demographics
WORLD_GEOGRAPHY_DATA: list[dict[str, Any]] = [
    {
        "category": "geography",
        "domain": "global_geography",
        "title": "World Geography, Continental Systems, and Major River Basins",
        "text": (
            "The Earth's surface comprises 7 continents and 5 major oceans:\n\n"
            "1. **Continents**: Asia (largest by area and population), Africa, North America, South America, Antarctica, Europe, Australia/Oceania.\n"
            "2. **Major Oceans**: Pacific (deepest & largest, containing the Mariana Trench), Atlantic, Indian, Southern, Arctic.\n"
            "3. **Major Global River Systems**:\n"
            "   - **Amazon River** (South America): Highest water discharge on Earth.\n"
            "   - **Nile River** (Africa): Longest river system in the world.\n"
            "   - **Ganga-Brahmaputra System** (India/Bangladesh): Forms the Sundarbans, the largest river delta on Earth.\n"
            "   - **Yangtze & Yellow Rivers** (China): Lifelines of East Asian civilization."
        ),
    },
]

# 4. Computer Science, Mathematics & Modern AI Architecture
CS_AND_AI_DATA: list[dict[str, Any]] = [
    {
        "category": "computer_science",
        "domain": "modern_ai_architectures",
        "title": "Modern Sovereign LLM Architecture: GQA, RoPE, SwiGLU, and FlashAttention-3",
        "text": (
            "The sovereign **IndicLLM-Bharat** architecture incorporates state-of-the-art transformer innovations:\n\n"
            "1. **Grouped-Query Attention (GQA)**:\n"
            "   - Partitions query heads into G groups, where all query heads within a group share a single Key and Value head ($H_{kv} = H_q / G$).\n"
            "   - Reduces KV-cache memory bandwidth by 4x–8x while maintaining Multi-Head Attention (MHA) modeling capacity.\n\n"
            "2. **Rotary Position Embeddings (RoPE)**:\n"
            "   - Encodes token positional information by multiplying 2D query/key subvectors by orthogonal 2D rotation matrices $R_{\\Theta, m}$:\n"
            "     \\[ R_{\\Theta, m} = \\begin{pmatrix} \\cos(m\\theta_i) & -\\sin(m\\theta_i) \\\\ \\sin(m\\theta_i) & \\cos(m\\theta_i) \\end{pmatrix} \\]\n"
            "   - Preserves relative token distances and facilitates long-context generalization up to 32k+ tokens.\n\n"
            "3. **SwiGLU Activation Function**:\n"
            "   - Non-linear gated feedforward activation: $\\text{SwiGLU}(x) = (xW \\cdot \\sigma(xW)) \\odot (xV)$.\n"
            "   - Outperforms standard ReLU and GELU activations in gradient flow and representation capacity.\n\n"
            "4. **RMSNorm (Root Mean Square Layer Normalization)**:\n"
            "   - Replaces traditional LayerNorm mean-centering with scale-only normalization: $\\text{RMSNorm}(x) = \\frac{x}{\\text{RMS}(x)} \\odot g$, saving memory operations."
        ),
    },
    {
        "category": "mathematics",
        "domain": "linear_algebra_calculus",
        "title": "Linear Algebra, Differential Equations, and Matrix Decomposition",
        "text": (
            "Foundations of mathematical modeling and neural network computation:\n\n"
            "1. **Singular Value Decomposition (SVD)**:\n"
            "   - Any matrix $A \\in \\mathbb{R}^{m \\times n}$ can be factored as $A = U \\Sigma V^T$, where $U$ and $V$ are orthogonal matrices and $\\Sigma$ contains singular values.\n"
            "   - Fundamental for low-rank matrix approximation (LoRA), principal component analysis (PCA), and embedding compression.\n\n"
            "2. **Eigenvalues and Eigenvectors**:\n"
            "   - $A v = \\lambda v$, where $\\lambda$ is the scalar eigenvalue and $v$ is the non-zero eigenvector.\n\n"
            "3. **Multivariate Calculus & Optimization**:\n"
            "   - **Gradient Descent & Backpropagation**: Chain rule computation of loss gradients $\\frac{\\partial \\mathcal{L}}{\\partial W}$ across composite computational graphs."
        ),
    },
]

# 5. All 22 Scheduled Indian Languages Curriculum
INDIC_22_LANGUAGES_DATA: list[dict[str, Any]] = [
    {
        "lang": "hi",
        "name": "Hindi (हिन्दी)",
        "category": "indic_linguistics",
        "title": "हिन्दी साहित्य एवं भाषा विकास",
        "text": (
            "हिन्दी भारत की प्रमुख संपर्क एवं राजभाषा है, जिसकी लिपि देवनागरी है। हिन्दी साहित्य का इतिहास "
            "चार प्रमुख कालों में विभाजित है: आदिकाल (वीरगाथा काल), भक्तिकाल (स्वर्ण युग - कबीर, तुलसी, सूर, जायसी), "
            "रीतिकाल, और आधुनिक काल (भारतेन्दु हरिश्चंद्र, जयशंकर प्रसाद, मुंशी प्रेमचंद, सूर्यकांत त्रिपाठी 'निराला')।"
        ),
    },
    {
        "lang": "bn",
        "name": "Bengali (বাংলা)",
        "category": "indic_linguistics",
        "title": "বাংলা সাহিত্য ও সাংস্কৃতিক ঐতিহ্য",
        "text": (
            "বাংলা ভাষা ইন্দো-আর্য ভাষাগোষ্ঠীর অন্তর্গত এবং বিশ্বের অন্যতম সমৃদ্ধ সাহিত্যিক ঐতিহ্যের অধিকারী। "
            "চর্যাপদ থেকে শুরু করে মধ্যযুগের মঙ্গলকাব্য, এবং আধুনিক যুগের ঈশ্বরচন্দ্র বিদ্যাসাগর, মাইকেল মধুসূদন দত্ত, "
            "বঙ্কিমচন্দ্র চট্টোপাধ্যায়, রবীন্দ্রনাথ ঠাকুর ও কাজী নজরুল ইসলামের অবদানে বাংলা সাহিত্য আন্তর্জাতিক মর্যাদায় প্রতিষ্ঠিত।"
        ),
    },
    {
        "lang": "ta",
        "name": "Tamil (தமிழ்)",
        "category": "indic_linguistics",
        "title": "தமிழ் செம்மொழி மற்றும் சங்க இலக்கியம்",
        "text": (
            "தமிழ் உலகிலேயே மிகத் தொன்மையான செம்மொழிகளில் ஒன்றாகும். இரண்டாயிரத்திற்கும் மேற்பட்ட ஆண்டுகள் பழமையான "
            "சங்க இலக்கியம் (எட்டுத்தொகை, பத்துப்பாட்டு), தொல்காப்பியம் (இலக்கண நூல்), திருக்குறள், மற்றும் ஐம்பெருங்காப்பியங்கள் "
            "(சிலப்பதிகாரம், மணிமேகலை) தமிழின் உயர் சிந்தனையை பறைசாற்றுகின்றன."
        ),
    },
    {
        "lang": "te",
        "name": "Telugu (తెలుగు)",
        "category": "indic_linguistics",
        "title": "తెలుగు భాషా వైభవం మరియు ప్రబంధ యుగం",
        "text": (
            "తెలుగు ద్రావిడ భాషా కుటుంబంలో అత్యధిక ప్రజలు మాట్లాడే భాష. కవిత్రయం (నన్నయ, తిక్కన, ఎర్రన) మహాభారతాన్ని "
            "ఆంధ్రీకరించారు. శ్రీకృష్ణదేవరాయల కాలం ప్రబంధ యుగంగా విలసిల్లింది, ఆయన రచించిన 'ఆముక్తమాల్యద' మరియు అల్లసాని పెద్దన "
            "'మనుచరిత్ర' తెలుగు సాహిత్య రత్నాలు."
        ),
    },
    {
        "lang": "mr",
        "name": "Marathi (मराठी)",
        "category": "indic_linguistics",
        "title": "मराठी भाषा, संत साहित्य आणि आधुनिक ज्ञान",
        "text": (
            "मराठी ही समृद्ध ऐतिहासिक वारसा लाभलेली अभिजात भाषा आहे. संत ज्ञानेश्वर, संत तुकाराम, संत नामदेव, आणि "
            "संत एकनाथ यांनी वारकरी संप्रदायाच्या माध्यमातून सामाजिक एकात्मतेचा संदेश दिला. छत्रपती शिवाजी महाराजांच्या "
            "स्वराज्यात मराठी भाषा प्रशासनाची प्रमुख भाषा बनली."
        ),
    },
    {
        "lang": "gu",
        "name": "Gujarati (ગુજરાતી)",
        "category": "indic_linguistics",
        "title": "ગુજરાતી સાહિત્ય અને સાંસ્કૃતિક ઓળખ",
        "text": (
            "ગુજરાતી ભાષાનો ઉદ્ભવ ગુર્જર અપભ્રંશમાંથી થયો છે. નરસિંહ મહેતાના ભક્તિપદો ('વૈષ્ણવ જન તો'), મીરાંબાઈ, દલપતરામ, "
            "નર્મદ, ગોવર્ધનરામ ત્રિપાઠી ('સરસ્વતીચંદ્ર'), અને ઝવેરચંદ મેઘાણીએ ગુજરાતી સાહિત્યને સમૃદ્ધ બનાવ્યું છે."
        ),
    },
    {
        "lang": "kn",
        "name": "Kannada (ಕನ್ನಡ)",
        "category": "indic_linguistics",
        "title": "ಕನ್ನಡ ಸಾಹಿತ್ಯ ಮತ್ತು ಜ್ಞಾನಪೀಠ ಪರಂಪರೆ",
        "text": (
            "ಕನ್ನಡವು ಭಾರತದ ಪ್ರಾಚೀನ ಶಾಸ್ತ್ರೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ. 'ಕವಿರಾಜಮಾರ್ಗ' (ಕ್ರಿ.ಶ. ೯ನೇ ಶತಮಾನ) ಕನ್ನಡದ ಉಪಲಬ್ಧ ಮೊದಲ "
            "ಸಾಹಿತ್ಯಿಕ ಕೃತಿ. ಪಂಪ, ರನ್ನ, ಪೊನ್ನ (ರತ್ನತ್ರಯರು), ವಚನಕಾರರು, ದಾಸ ಸಾಹಿತ್ಯ, ಮತ್ತು ಕುವೆಂಪು, ಬೇಂದ್ರೆ, ಕಾರಂತ ಸೇರಿದಂತೆ "
            "೮ ಜ್ಞಾನಪೀಠ ಪ್ರಶಸ್ತಿ ವಿಜೇತರು ಕನ್ನಡಕ್ಕೆ ಅಪಾರ ಕೀರ್ತಿ ತಂದಿದ್ದಾರೆ."
        ),
    },
    {
        "lang": "ml",
        "name": "Malayalam (മലയാളം)",
        "category": "indic_linguistics",
        "title": "മലയാള സാഹിത്യവും ഭാഷാ പിതാവും",
        "text": (
            "മലയാള ഭാഷയുടെ പിതാവായി തുഞ്ചത്തെഴുത്തച്ഛൻ (അദ്ധ്യാത്മരാമായണം കിളിപ്പാട്ട്) ആദരിക്കപ്പെടുന്നു. കുഞ്ചൻ നമ്പ്യാരുടെ "
            "തുള്ളൽ പ്രസ്ഥാനം, വള്ളത്തോൾ, ഉള്ളൂർ, കുമാരനാശാൻ (ആധുനിക കവിത്രയം) എന്നിവർ മലയാള സാഹിത്യത്തിന് ശക്തമായ അടിത്തറ നൽകി."
        ),
    },
    {
        "lang": "pa",
        "name": "Punjabi (ਪੰਜਾਬੀ)",
        "category": "indic_linguistics",
        "title": "ਪੰਜਾਬੀ ਭਾਸ਼ਾ ਅਤੇ ਗੁਰਮੁਖੀ ਲਿਪੀ",
        "text": (
            "ਪੰਜਾਬੀ ਭਾਸ਼ਾ ਗੁਰਮੁਖੀ ਲਿਪੀ ਵਿੱਚ ਲਿਖੀ ਜਾਂਦੀ ਹੈ। ਬਾਬਾ ਫਰੀਦ ਜੀ, ਗੁਰੂ ਨਾਨਕ ਦੇਵ ਜੀ, ਗੁਰੂ ਅਰਜਨ ਦੇਵ ਜੀ (ਸ੍ਰੀ ਗੁਰੂ ਗ੍ਰੰਥ ਸਾਹਿਬ), "
            "ਅਤੇ ਵਾਰਿਸ ਸ਼ਾਹ (ਹੀਰ ਵਾਰਿਸ ਸ਼ਾਹ), ਬੁੱਲ੍ਹੇ ਸ਼ਾਹ, ਅਤੇ ਅੰਮ੍ਰਿਤਾ ਪ੍ਰੀਤਮ ਨੇ ਪੰਜਾਬੀ ਸਾਹਿਤ ਨੂੰ ਵਿਸ਼ਵ ਪੱਧਰ 'ਤੇ ਮਾਨਤਾ ਦਿਵਾਈ।"
        ),
    },
    {
        "lang": "or",
        "name": "Odia (ଓଡ଼ିଆ)",
        "category": "indic_linguistics",
        "title": "ଓଡ଼ିଆ ଶାସ୍ତ୍ରୀୟ ଭାଷା ଓ ସାହିତ୍ୟ",
        "text": (
            "ଓଡ଼ିଆ ଭାରତର ଏକ ପ୍ରାଚୀନ ଶାସ୍ତ୍ରୀୟ ଭାଷା। ସାରଳା ଦାସଙ୍କ 'ସାରଳା ମହାଭାରତ', ପଞ୍ଚସଖା ସାହିତ୍ୟ (ଜଗନ୍ନାଥ ଦାସଙ୍କ 'ଭାଗବତ'), "
            "ଉପେନ୍ଦ୍ର ଭଞ୍ଜଙ୍କ ରୀତିକାବ୍ୟ ଏବଂ ଫକୀର ମୋହନ ସେନାପତିଙ୍କ 'ଛ' ମାଣ ଆଠ ଗୁଣ୍ଠ' ଓଡ଼ିଆ ସାହିତ୍ୟର ଅମୂଲ୍ୟ ସମ୍ପଦ।"
        ),
    },
    {
        "lang": "as",
        "name": "Assamese (অসমীয়া)",
        "category": "indic_linguistics",
        "title": "অসমীয়া ভাষা আৰু শংকৰদেৱৰ বৰঙণি",
        "text": (
            "অসমীয়া ভাষা উত্তৰ-পূব ভাৰতৰ প্ৰধান সংযোগী ভাষা। পঞ্চদশ শতিকাত শ্ৰীমন্ত শংকৰদেৱ আৰু মাধৱদেৱৰ বৈষ্ণৱ আন্দোলন, "
            "বৰগীত, অংকীয়া নাট আৰু বুৰঞ্জী সাহিত্যই অসমীয়া জাতিক ঐক্যবদ্ধ আৰু সাহিত্যক সমৃদ্ধিশালী কৰি তোলে।"
        ),
    },
    {
        "lang": "ur",
        "name": "Urdu (اردو)",
        "category": "indic_linguistics",
        "title": "اردو زبان، شاعری اور ادبی تاریخ",
        "text": (
            "اردو ہندوستان کی ایک خوبصورت اور شیریں زبان ہے جو گنگا-جمنی تہذیب کی علامت ہے۔ "
            "میر تقی میر، مرزا اسد اللہ خان غالب، علامہ اقبال، اور فیض احمد فیض کی شاعری نے اردو کو عالمی شہرت بخشی۔"
        ),
    },
    {
        "lang": "sa",
        "name": "Sanskrit (संस्कृतम्)",
        "category": "indic_linguistics",
        "title": "संस्कृतभाषायाः महत्त्वं वैज्ञानिकदृष्टिकोणश्च",
        "text": (
            "संस्कृतभाषा भारतस्य प्राचीना देवभाषा, सर्वासामार्यभाषाणां जननी च। पाणिनिना विरचिता 'अष्टाध्यायी' "
            "व्याकरणशास्त्रस्य सर्वोत्कृष्टं प्रमाणम्। वेदारण्यकोपनिषदः, रामायणम्, महाभारतम्, कालिदासस्य नाटकानि "
            "च संस्कृतस्य गौरवग्रन्थाः सन्ति।"
        ),
    },
]


def get_all_world_knowledge_documents() -> list[dict[str, Any]]:
    """Return all combined world knowledge documents."""
    return (
        GLOBAL_SCIENCE_DATA
        + WORLD_HISTORY_DATA
        + WORLD_GEOGRAPHY_DATA
        + CS_AND_AI_DATA
        + INDIC_22_LANGUAGES_DATA
    )


def export_world_knowledge_corpus(output_path: str | Path) -> int:
    """Export complete world knowledge corpus to JSONL format."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    docs = get_all_world_knowledge_documents()
    with open(out, "w", encoding="utf-8") as f:
        for doc in docs:
            f.write(json.dumps(doc, ensure_ascii=False) + "\n")

    return len(docs)


def pack_world_knowledge_shards(
    tokenizer: BharatTokenizer,
    output_dir: str | Path,
    max_tokens_per_shard: int = 500_000,
) -> list[Path]:
    """Export world knowledge corpus and pack directly into binary token shards."""
    corpus_tmp = Path(output_dir) / "_world_corpus_temp.jsonl"
    export_world_knowledge_corpus(corpus_tmp)

    shards = pack_text_corpus(
        tokenizer=tokenizer,
        input_file=corpus_tmp,
        output_dir=output_dir,
        prefix="bharat_world_shard",
        max_tokens_per_shard=max_tokens_per_shard,
    )

    if corpus_tmp.is_file():
        corpus_tmp.unlink()

    return shards
